# /srv/compose.yaml

services:

  caddy:
    image: "caddy:2-alpine"
    container_name: "caddy"
    ports:
      - "80:80"
    volumes:
      - "./caddy/data:/data"
      - "./caddy/config:/config"
      - "./caddy/conf:/etc/caddy:ro"
    restart: "unless-stopped"

  dashy:
    image: "lissy93/dashy:latest"
    container_name: "dashy"
    user: "1000:1000"
    environment:
      NODE_ENV: "production"
    volumes:
      - "./dashy/user-data:/app/user-data"
    restart: "unless-stopped"

  pihole:
    image: "pihole/pihole:latest"
    container_name: "pihole"
    environment:
      TZ: "Europe/Warsaw"
      PIHOLE_GID: "1000"
      PIHOLE_UID: "1000"
      FTLCONF_dns_upstreams: "1.1.1.1;1.0.0.1"
      FTLCONF_dns_listeningMode: "ALL"
      FTLCONF_webserver_api_password: "${PIHOLE_WEB_PASSWORD}"
      FTLCONF_webserver_paths_prefix: "/pihole"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./pihole/etc-pihole:/etc/pihole"
    restart: "unless-stopped"

  sonarr:
    image: "lscr.io/linuxserver/sonarr:latest"
    container_name: "sonarr"
    environment:
      TZ: "Europe/Warsaw"
      PUID: "1000"
      PGID: "1000"
      SONARR__SERVER__URLBASE: "/sonarr"
    volumes:
      - "./storage/data:/data"
      - "./sonarr/config:/config"
    restart: "unless-stopped"

  radarr:
    image: "lscr.io/linuxserver/radarr:latest"
    container_name: "radarr"
    environment:
      TZ: "Europe/Warsaw"
      PUID: "1000"
      PGID: "1000"
      RADARR__SERVER__URLBASE: "/radarr"
    volumes:
      - "./storage/data:/data"
      - "./radarr/config:/config"
    restart: "unless-stopped"

  bazarr:
    image: "lscr.io/linuxserver/bazarr:latest"
    container_name: "bazarr"
    environment:
      TZ: "Europe/Warsaw"
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "./bazarr/config:/config"
      - "./storage/data/media:/data/media"
    restart: "unless-stopped"

  jellyfin:
    image: "jellyfin/jellyfin:latest"
    container_name: "jellyfin"
    user: "1000:1000"
    group_add:
      - "992"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    ports:
      - "7359:7359/udp"
    volumes:
      - "./jellyfin/cache:/cache"
      - "./jellyfin/config:/config"
      - "./storage/data/media:/data/media:ro"
    restart: "unless-stopped"

  prowlarr:
    image: "lscr.io/linuxserver/prowlarr:latest"
    container_name: "prowlarr"
    environment:
      TZ: "Europe/Warsaw"
      PUID: "1000"
      PGID: "1000"
      PROWLARR__SERVER__URLBASE: "/prowlarr"
    volumes:
      - "./prowlarr/config:/config"
    restart: "unless-stopped"

  qbittorrent:
    image: "lscr.io/linuxserver/qbittorrent:latest"
    container_name: "qbittorrent"
    environment:
      TZ: "Europe/Warsaw"
      PGID: "1000"
      PUID: "1000"
      WEBUI_PORT: "8080"
      DOCKER_MODS: "ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest"
      TORRENTING_PORT: "6881"
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "./qbittorrent/config:/config"
      - "./storage/data/torrents:/data/torrents"
    restart: "unless-stopped"

  filebrowser:
    image: "filebrowser/filebrowser:latest"
    container_name: "filebrowser"
    environment:
      FB_BASE_URL: "/filebrowser"
    volumes:
      - "./storage/data:/srv"
      - "./filebrowser/config:/config"
      - "./filebrowser/database:/database"
    restart: "unless-stopped"

  cup:
    image: "ghcr.io/sergi0g/cup:latest"
    container_name: "cup"
    user: "1000:987"
    environment:
      TZ: "Europe/Warsaw"
    command: "serve"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: "unless-stopped"
