# /srv/dashy/user-data/conf.yml

pageInfo:
  title: Home Server
  description: debian.local
  navLinks:
    - title: Documentation
      path: https://dashy.to/docs
appConfig:
  theme: adventure
  defaultOpeningMethod: sametab
  statusCheck: true
  statusCheckInterval: 0
  language: en
  webSearch:
    disableWebSearch: true
  hideComponents:
    hideSearch: true
sections:
  - name: Media
    items:
      - title: Jellyfin
        description: Media server
        icon: si-jellyfin
        url: /jellyfin/
        statusCheck: true
        statusCheckUrl: http://jellyfin:8096/jellyfin/
      - title: qBittorrent
        description: Torrent client
        icon: si-qbittorrent
        url: /qbt/
        statusCheck: true
        statusCheckUrl: http://qbittorrent:8080/
      - title: File Browser
        description: Web file manager
        icon: si-files
        url: /filebrowser/
        statusCheck: true
        statusCheckUrl: http://caddy/filebrowser/
  - name: Network
    items:
      - title: Pi-hole
        description: DNS filtering
        icon: si-pihole
        url: /pihole/admin/
        statusCheck: true
        statusCheckUrl: http://pihole:80/admin/login
